name: Python CI + NTFY

on:
  push:

jobs:
  test-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Ejecutar pruebas unitarias
        run: |
          pytest -v

      - name: Enviar notificacion
        if: success()
        run: |
          curl -H "Title: CI Exitosa" \
               -H "Tags: white_check_mark,github" \
               -d "Pruebas OK en ${{ github.repository }}. Push realizado por ${{ github.actor }}" \
               https://ntfy.sh/devops-itla

      - name: Enviar notificacion de error
        if: failure()
        run: |
          curl -H "Title: CI Fallida" \
               -H "Priority: high" \
               -H "Tags: x,github" \
               -d "Fallaron las pruebas en ${{ github.repository }}" \
               https://ntfy.sh/devops-itla